import http from "node:http";
import { toJsonSchema, validate, applyDefaults } from "./schema.js";

export { s } from "./schema.js";

/**
 * defineAgentConfig: the one file a site owner writes.
 * tools: { name: { description, input, readOnly?, auth?: "none"|"session"|"oauth", confirm?, handler(input, ctx) } }
 */
export function defineAgentConfig(cfg) {
  const tools = {};
  for (const [name, t] of Object.entries(cfg.tools)) {
    if (typeof t.handler !== "function") throw new Error(`tool ${name}: handler must be a function`);
    tools[name] = {
      name,
      description: t.description || name,
      inputSchema: toJsonSchema(t.input),
      readOnly: !!t.readOnly,
      auth: t.auth || (t.readOnly ? "none" : "session"),
      confirm: t.confirm ?? !t.readOnly,
      handler: t.handler,
    };
  }
  return { site: cfg.site, description: cfg.description || "", baseUrl: cfg.baseUrl, pages: cfg.pages || [], tools };
}

/* ---------- generated surfaces ---------- */

export function agentsTxt(cfg) {
  return [
    `# agents.txt for ${cfg.site}`,
    `# Generated by actorial. Same information in JSON at /.well-known/agents.json`,
    `Site: ${cfg.site}`,
    `Authorization: session, oauth2`,
    `MCP: ${cfg.baseUrl}/mcp`,
    `UCP: ${cfg.baseUrl}/.well-known/ucp`,
    `WebMCP: ${cfg.baseUrl}/`,
    `OpenAPI: ${cfg.baseUrl}/openapi.json`,
    `LLMs: ${cfg.baseUrl}/llms.txt`,
    ``,
  ].join("\n");
}

export function agentsJson(cfg) {
  return {
    version: "0.1",
    site: cfg.site,
    description: cfg.description,
    authorization: ["session", "oauth2"],
    mcp: `${cfg.baseUrl}/mcp`,
    ucp: `${cfg.baseUrl}/.well-known/ucp`,
    webmcp: [`${cfg.baseUrl}/`],
    openapi: `${cfg.baseUrl}/openapi.json`,
    llms: `${cfg.baseUrl}/llms.txt`,
    tools: Object.values(cfg.tools).map(t => ({
      name: t.name, description: t.description, readOnly: t.readOnly, auth: t.auth, confirm: t.confirm,
    })),
  };
}

export function llmsTxt(cfg) {
  const lines = [`# ${cfg.site}`, ``, `> ${cfg.description}`, ``, `## Agent tools`, ``];
  for (const t of Object.values(cfg.tools)) {
    const params = Object.keys(t.inputSchema.properties || {}).join(", ");
    lines.push(`- ${t.name}(${params}): ${t.description}${t.readOnly ? "" : " [write, needs confirmation]"}`);
  }
  lines.push(``, `## Endpoints`, ``, `- MCP: ${cfg.baseUrl}/mcp`, `- OpenAPI: ${cfg.baseUrl}/openapi.json`, ``);
  return lines.join("\n");
}

// Universal Commerce Protocol discovery manifest. Same shape Shopify serves per store since Aug 2026.
export function ucpManifest(cfg) {
  const names = Object.keys(cfg.tools);
  const has = (n) => names.includes(n);
  return {
    ucp: {
      version: "2026-08-25",
      services: {
        "dev.ucp.shopping": {
          version: "2026-08-25",
          spec: "https://ucp.dev/specification/overview",
          rest: `${cfg.baseUrl}/api/ucp`,
          mcp: `${cfg.baseUrl}/api/ucp/mcp`,
        },
      },
      capabilities: [
        has("search_catalog") && { name: "dev.ucp.shopping.catalog", version: "2026-08-25" },
        has("update_cart") && { name: "dev.ucp.shopping.cart", version: "2026-08-25" },
      ].filter(Boolean),
    },
    merchant: { name: cfg.site, url: cfg.baseUrl },
  };
}

export function openapiJson(cfg) {
  const paths = {};
  for (const t of Object.values(cfg.tools)) {
    paths[`/api/${t.name}`] = {
      post: {
        operationId: t.name,
        summary: t.description,
        "x-readOnly": t.readOnly,
        "x-auth": t.auth,
        requestBody: { required: true, content: { "application/json": { schema: t.inputSchema } } },
        responses: { 200: { description: "Result", content: { "application/json": { schema: { type: "object" } } } } },
      },
    };
  }
  return { openapi: "3.1.0", info: { title: `${cfg.site} agent API`, version: "0.1.0" }, servers: [{ url: cfg.baseUrl }], paths };
}

/* ---------- tool execution ---------- */

export async function callTool(cfg, name, rawInput, ctx = {}) {
  const t = cfg.tools[name];
  if (!t) return { error: `unknown tool: ${name}` };
  const input = applyDefaults(t.inputSchema, rawInput || {});
  const errs = validate(t.inputSchema, input);
  if (errs.length) return { error: "invalid input", details: errs };
  if (t.auth === "session" && !ctx.session) return { error: "auth required", auth: "session" };
  if (t.auth === "oauth" && !ctx.token) return { error: "auth required", auth: "oauth2" };
  if (t.confirm && !ctx.confirmed) return { error: "confirmation required", confirm: true, tool: name, input };
  const result = await t.handler(input, ctx);
  return { result };
}

/* ---------- browser script (WebMCP act layer) ---------- */

export function browserScript(cfg) {
  const tools = Object.values(cfg.tools).map(t => ({
    name: t.name, description: t.description, inputSchema: t.inputSchema, readOnly: t.readOnly, confirm: t.confirm,
  }));
  return `// actorial runtime: registers this page's tools with the browser agent layer (WebMCP).
(function () {
  const tools = ${JSON.stringify(tools)};
  async function call(name, input, confirmed) {
    const r = await fetch("/api/" + name, { method: "POST", credentials: "include",
      headers: { "content-type": "application/json", "x-actorial-confirmed": confirmed ? "1" : "0" },
      body: JSON.stringify(input) });
    return r.json();
  }
  const mc = navigator.modelContext;
  if (!mc || typeof mc.registerTool !== "function") {
    window.__actorial = { tools, call, webmcp: false };
    return; // no-op where WebMCP is missing
  }
  for (const t of tools) {
    mc.registerTool({
      name: t.name, description: t.description, inputSchema: t.inputSchema,
      annotations: { readOnlyHint: t.readOnly },
      async execute(input) {
        let confirmed = false;
        if (t.confirm) confirmed = window.confirm("Agent wants to run " + t.name + " with " + JSON.stringify(input) + ". Allow?");
        if (t.confirm && !confirmed) return { content: [{ type: "text", text: "User declined" }], isError: true };
        const out = await call(t.name, input, confirmed);
        return { content: [{ type: "text", text: JSON.stringify(out) }] };
      },
    });
  }
  window.__actorial = { tools, call, webmcp: true };
})();`;
}

/* ---------- server ---------- */

export function createServer(cfg, opts = {}) {
  const renderPage = opts.renderPage || (() => `<!doctype html><title>${cfg.site}</title><h1>${cfg.site}</h1><p>${cfg.description}</p><script src="/actorial.js"></script>`);

  const json = (res, code, body) => { res.writeHead(code, { "content-type": "application/json" }); res.end(JSON.stringify(body)); };
  const text = (res, body, type = "text/plain; charset=utf-8") => { res.writeHead(200, { "content-type": type }); res.end(body); };
  const readBody = (req) => new Promise((resolve) => { let b = ""; req.on("data", c => b += c); req.on("end", () => { try { resolve(b ? JSON.parse(b) : {}); } catch { resolve({}); } }); });

  const ctxFrom = (req) => ({
    session: req.headers.cookie?.includes("session=") ? { user: "takis" } : (req.headers.authorization ? { user: "takis" } : null),
    token: req.headers.authorization?.replace(/^Bearer /, "") || null,
    confirmed: req.headers["x-actorial-confirmed"] === "1",
  });

  return http.createServer(async (req, res) => {
    const url = new URL(req.url, cfg.baseUrl);
    const p = url.pathname;

    if (p === "/.well-known/agents.txt" || p === "/agents.txt") return text(res, agentsTxt(cfg));
    if (p === "/.well-known/agents.json" || p === "/agents.json") return json(res, 200, agentsJson(cfg));
    if (p === "/llms.txt") return text(res, llmsTxt(cfg), "text/markdown; charset=utf-8");
    if (p === "/openapi.json") return json(res, 200, openapiJson(cfg));
    if (p === "/.well-known/ucp") return json(res, 200, ucpManifest(cfg));
    if (p === "/actorial.js") return text(res, browserScript(cfg), "text/javascript");

    if (p.startsWith("/api/") && p !== "/api/ucp/mcp" && req.method === "POST") {
      const name = p.slice(5);
      const body = await readBody(req);
      const out = await callTool(cfg, name, body, ctxFrom(req));
      return json(res, out.error ? 400 : 200, out);
    }

    if ((p === "/mcp" || p === "/api/ucp/mcp") && req.method === "POST") {
      const rpc = await readBody(req);
      const reply = (result) => json(res, 200, { jsonrpc: "2.0", id: rpc.id, result });
      if (rpc.method === "initialize") return reply({ protocolVersion: "2025-06-18", serverInfo: { name: `${cfg.site} actorial`, version: "0.1.0" }, capabilities: { tools: {} } });
      if (rpc.method === "tools/list") return reply({ tools: Object.values(cfg.tools).map(t => ({ name: t.name, description: t.description, inputSchema: t.inputSchema, annotations: { readOnlyHint: t.readOnly } })) });
      if (rpc.method === "tools/call") {
        const ctx = ctxFrom(req);
        if (rpc.params?._meta?.confirmed) ctx.confirmed = true;
        const out = await callTool(cfg, rpc.params?.name, rpc.params?.arguments, ctx);
        return reply({ content: [{ type: "text", text: JSON.stringify(out.error ? out : out.result) }], isError: !!out.error });
      }
      return json(res, 200, { jsonrpc: "2.0", id: rpc.id, error: { code: -32601, message: "method not found" } });
    }

    if (p === "/" || p.startsWith("/p/") || p.startsWith("/search")) return text(res, await renderPage(url), "text/html; charset=utf-8");
    res.writeHead(404); res.end("not found");
  });
}
